// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.2
// source: arithmetic.proto

package arithmetic

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ArithmeticClient is the client API for Arithmetic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArithmeticClient interface {
	Add(ctx context.Context, in *Many, opts ...grpc.CallOption) (*One, error)
	Sub(ctx context.Context, in *Many, opts ...grpc.CallOption) (*One, error)
	Mul(ctx context.Context, in *Many, opts ...grpc.CallOption) (*One, error)
	Div(ctx context.Context, in *Many, opts ...grpc.CallOption) (*One, error)
}

type arithmeticClient struct {
	cc grpc.ClientConnInterface
}

func NewArithmeticClient(cc grpc.ClientConnInterface) ArithmeticClient {
	return &arithmeticClient{cc}
}

func (c *arithmeticClient) Add(ctx context.Context, in *Many, opts ...grpc.CallOption) (*One, error) {
	out := new(One)
	err := c.cc.Invoke(ctx, "/Arithmetic/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arithmeticClient) Sub(ctx context.Context, in *Many, opts ...grpc.CallOption) (*One, error) {
	out := new(One)
	err := c.cc.Invoke(ctx, "/Arithmetic/Sub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arithmeticClient) Mul(ctx context.Context, in *Many, opts ...grpc.CallOption) (*One, error) {
	out := new(One)
	err := c.cc.Invoke(ctx, "/Arithmetic/Mul", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arithmeticClient) Div(ctx context.Context, in *Many, opts ...grpc.CallOption) (*One, error) {
	out := new(One)
	err := c.cc.Invoke(ctx, "/Arithmetic/Div", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArithmeticServer is the server API for Arithmetic service.
// All implementations must embed UnimplementedArithmeticServer
// for forward compatibility
type ArithmeticServer interface {
	Add(context.Context, *Many) (*One, error)
	Sub(context.Context, *Many) (*One, error)
	Mul(context.Context, *Many) (*One, error)
	Div(context.Context, *Many) (*One, error)
	mustEmbedUnimplementedArithmeticServer()
}

// UnimplementedArithmeticServer must be embedded to have forward compatible implementations.
type UnimplementedArithmeticServer struct {
}

func (UnimplementedArithmeticServer) Add(context.Context, *Many) (*One, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedArithmeticServer) Sub(context.Context, *Many) (*One, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sub not implemented")
}
func (UnimplementedArithmeticServer) Mul(context.Context, *Many) (*One, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mul not implemented")
}
func (UnimplementedArithmeticServer) Div(context.Context, *Many) (*One, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Div not implemented")
}
func (UnimplementedArithmeticServer) mustEmbedUnimplementedArithmeticServer() {}

// UnsafeArithmeticServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArithmeticServer will
// result in compilation errors.
type UnsafeArithmeticServer interface {
	mustEmbedUnimplementedArithmeticServer()
}

func RegisterArithmeticServer(s grpc.ServiceRegistrar, srv ArithmeticServer) {
	s.RegisterService(&Arithmetic_ServiceDesc, srv)
}

func _Arithmetic_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Many)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithmeticServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Arithmetic/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithmeticServer).Add(ctx, req.(*Many))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arithmetic_Sub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Many)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithmeticServer).Sub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Arithmetic/Sub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithmeticServer).Sub(ctx, req.(*Many))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arithmetic_Mul_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Many)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithmeticServer).Mul(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Arithmetic/Mul",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithmeticServer).Mul(ctx, req.(*Many))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arithmetic_Div_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Many)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithmeticServer).Div(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Arithmetic/Div",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithmeticServer).Div(ctx, req.(*Many))
	}
	return interceptor(ctx, in, info, handler)
}

// Arithmetic_ServiceDesc is the grpc.ServiceDesc for Arithmetic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Arithmetic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Arithmetic",
	HandlerType: (*ArithmeticServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Arithmetic_Add_Handler,
		},
		{
			MethodName: "Sub",
			Handler:    _Arithmetic_Sub_Handler,
		},
		{
			MethodName: "Mul",
			Handler:    _Arithmetic_Mul_Handler,
		},
		{
			MethodName: "Div",
			Handler:    _Arithmetic_Div_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arithmetic.proto",
}
