// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.2
// source: arithmetic.proto

package arithmetic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Many struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []float64 `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Many) Reset() {
	*x = Many{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arithmetic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Many) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Many) ProtoMessage() {}

func (x *Many) ProtoReflect() protoreflect.Message {
	mi := &file_arithmetic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Many.ProtoReflect.Descriptor instead.
func (*Many) Descriptor() ([]byte, []int) {
	return file_arithmetic_proto_rawDescGZIP(), []int{0}
}

func (x *Many) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type One struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *One) Reset() {
	*x = One{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arithmetic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *One) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*One) ProtoMessage() {}

func (x *One) ProtoReflect() protoreflect.Message {
	mi := &file_arithmetic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use One.ProtoReflect.Descriptor instead.
func (*One) Descriptor() ([]byte, []int) {
	return file_arithmetic_proto_rawDescGZIP(), []int{1}
}

func (x *One) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_arithmetic_proto protoreflect.FileDescriptor

var file_arithmetic_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x04, 0x4d, 0x61, 0x6e, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x22, 0x1b, 0x0a, 0x03, 0x4f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32,
	0x64, 0x0a, 0x0a, 0x41, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x12, 0x14, 0x0a,
	0x03, 0x41, 0x64, 0x64, 0x12, 0x05, 0x2e, 0x4d, 0x61, 0x6e, 0x79, 0x1a, 0x04, 0x2e, 0x4f, 0x6e,
	0x65, 0x22, 0x00, 0x12, 0x14, 0x0a, 0x03, 0x53, 0x75, 0x62, 0x12, 0x05, 0x2e, 0x4d, 0x61, 0x6e,
	0x79, 0x1a, 0x04, 0x2e, 0x4f, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x14, 0x0a, 0x03, 0x4d, 0x75, 0x6c,
	0x12, 0x05, 0x2e, 0x4d, 0x61, 0x6e, 0x79, 0x1a, 0x04, 0x2e, 0x4f, 0x6e, 0x65, 0x22, 0x00, 0x12,
	0x14, 0x0a, 0x03, 0x44, 0x69, 0x76, 0x12, 0x05, 0x2e, 0x4d, 0x61, 0x6e, 0x79, 0x1a, 0x04, 0x2e,
	0x4f, 0x6e, 0x65, 0x22, 0x00, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6b, 0x73, 0x69, 0x61, 0x6c, 0x2f, 0x73, 0x74, 0x64, 0x6c, 0x2f,
	0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x72,
	0x69, 0x74, 0x68, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x2f, 0x61, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x65,
	0x74, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_arithmetic_proto_rawDescOnce sync.Once
	file_arithmetic_proto_rawDescData = file_arithmetic_proto_rawDesc
)

func file_arithmetic_proto_rawDescGZIP() []byte {
	file_arithmetic_proto_rawDescOnce.Do(func() {
		file_arithmetic_proto_rawDescData = protoimpl.X.CompressGZIP(file_arithmetic_proto_rawDescData)
	})
	return file_arithmetic_proto_rawDescData
}

var file_arithmetic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_arithmetic_proto_goTypes = []interface{}{
	(*Many)(nil), // 0: Many
	(*One)(nil),  // 1: One
}
var file_arithmetic_proto_depIdxs = []int32{
	0, // 0: Arithmetic.Add:input_type -> Many
	0, // 1: Arithmetic.Sub:input_type -> Many
	0, // 2: Arithmetic.Mul:input_type -> Many
	0, // 3: Arithmetic.Div:input_type -> Many
	1, // 4: Arithmetic.Add:output_type -> One
	1, // 5: Arithmetic.Sub:output_type -> One
	1, // 6: Arithmetic.Mul:output_type -> One
	1, // 7: Arithmetic.Div:output_type -> One
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arithmetic_proto_init() }
func file_arithmetic_proto_init() {
	if File_arithmetic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_arithmetic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Many); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arithmetic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*One); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_arithmetic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arithmetic_proto_goTypes,
		DependencyIndexes: file_arithmetic_proto_depIdxs,
		MessageInfos:      file_arithmetic_proto_msgTypes,
	}.Build()
	File_arithmetic_proto = out.File
	file_arithmetic_proto_rawDesc = nil
	file_arithmetic_proto_goTypes = nil
	file_arithmetic_proto_depIdxs = nil
}
